### ISSUE TITLE
Build fills with dmd 2.070

### ISSUE THREAD

**Issue by gnunn1** [Pure-D/workspace-d#11]
I get the following error when trying to build workspace-d with dmd 2.070:

../../../.dub/packages/painlessjson-1.3.5/source/painlessjson/painlessjson.d(9,8): Error: module std.typecons import 'TypeTuple' not found, did you mean template 'isTypeTuple(T...)'?

**Comment by WebFreak001** [comment]
If it still not works use `dub upgrade`

**Comment by gnunn1** [comment]
Thanks, that did the trick.
