### ISSUE TITLE
Root package workspace-d references unknown package dub

### ISSUE THREAD

**Issue by catb0t** [Pure-D/workspace-d#13]
I've cloned this repo, and then:

``` sh
$ cd workspace-d
$ dub
Root package workspace-d references unknown package dub
```

It won't build. What am I doing wrong?

**Comment by WebFreak001** [comment]
other dub packages with dependencies work, right? Try running `dub upgrade` before running `dub`

**Comment by catb0t** [comment]
@WebFreak001 

``` sh
~/workspace-d(master) $ dub upgrade
Upgrading project in /home/cat/Downloads/misc/workspace-d
Root package workspace-d references unknown package dub
```

**Comment by Vild** [comment]
Your dub cache could be corrupt.
Run this and then try and run `dub` again
`rm ~/.dub/cache/*`

**Comment by catb0t** [comment]
The directory didn't exist, so I created it, and tried `dub upgrade`, which led to the same error. Then I removed the directory, and the same result. I built `dub` from source on Linux x64.

**Comment by Vild** [comment]
Does `dub fetch relationlist` work?

**Comment by catb0t** [comment]
Nope:

``` sh
~/workspace-d(master) $ dub fetch relationlist
Getting a release version failed: No package relationlist was found matching the dependency >=0.0.0
Retry with ~master...
No package relationlist was found matching the dependency ~master
```

**Comment by Vild** [comment]
Seems like your dub installation can't access code.dlang.org. Which is really weird...
Are you running v0.9.24 or the latest git version?

**Comment by WebFreak001** [comment]
Are you using a proxy? I'm not sure if its possible to let dub use a proxy on linux but on windows that doesn't work.
Also check your internet connection or try `curl http://code.dlang.org/api/packages/dub/latest`. It should say `"0.9.24"`

**Comment by catb0t** [comment]
No proxies here. I don't know what's up with this.

``` sh
$ curl http://code.dlang.org/api/packages/dub/latest
"0.9.24"
$ dub --version
DUB version 0.9.24+182-g7b9eba4, built on Mar 22 2016
```

**Comment by WebFreak001** [comment]
Does it work if you run `dub clean-caches && dub upgrade && dub`?
