### ISSUE TITLE
Unknown dependency: memutils

### ISSUE THREAD

**Issue by jvulcan** [Pure-D/workspace-d#14]
In Windows using dub --build=debug it outputs an error (see title).

Adding memutils dependeny fixed the error:

```
"dependencies":` {
        "dub": "~>0.9.24",
        "dunit": "~>1.0.12",
        "painlessjson": "~>1.3.6",
        "memutils": "~>0.4.5"
    },
```

**Comment by jvulcan** [comment]
Re-correcting:

In the first DUB build it throws error, even if memutils is listed in dependencies.
The second time it compiles.

Close the issue if needed.

**Comment by WebFreak001** [comment]
um just doing `dub upgrade` should have fixed that. For some reason dub doesn't care about packages being outdated and only tells the user that you can upgrade instead of upgrading if a version doesn't match
