### ISSUE TITLE
README is confusing to newbies.

### ISSUE THREAD

**Issue by klosworks** [Pure-D/workspace-d#17]
The README says

> Installation
> 
> Install the desired extra programs (dcd, dfmt, dscanner) if using them.
> 
> ```
> git clone https://github.com/Pure-D/workspace-d.git
> cd workspace-d
> dub build --build=release
> ```

It is not clear what is the relationship between the line "Install the desired extra programs (dcd, dfmt, dscanner) if using them." and the 3 following lines. It seems that the 3 lines ought to be the means to achieve the goal indicated by the "Install..." line, but its not the case.
This is confusing to newcomers who don't necessarily know what is the relationship between workspace-d-installer, workspace-d, dcd, dfmt and dscanner. It was confusing to me when I first looked at you projects.
The expression "desired extra programs" is not entirely clear either. Its better to replace with the standard engineering term "dependencies".
Also, is it a good idea to use workspace-d without any of (dcd, dfmt or dscanner)? No? Then its better to drop the "if using them" part. Its much better to send a very simple message "do this" rather than lots of ifs and remarks. Its because of the [Paradox of choice](https://en.wikipedia.org/wiki/The_Paradox_of_Choice).

The reformulated part of README becomes:

> Installation
> 
> First, install dependencies: 
> - [dcd](https://github.com/Hackerpilot/DCD)
> - [dfmt](https://github.com/Hackerpilot/dfmt)
> - [dscanner](https://github.com/Hackerpilot/Dscanner)
> 
> Then, run:
> 
> ```
> git clone https://github.com/Pure-D/workspace-d.git
> cd workspace-d
> dub build --build=release
> ```

**Comment by klosworks** [comment]
Actually, it is probably better to mention workspace-d-installer, if that is supposed to be the main way of installing workspace-d (otherwise, why would it exist?)

So then the readme would be 

> Installation
> 
> The most simple way is to use the 
> - **[workspace-d-installer](https://github.com/Pure-D/workspace-d-installer)**
> 
> Otherwise, perform manual installation:
> - First, install dependencies: 
>   - [dcd](https://github.com/Hackerpilot/DCD)
>   - [dfmt](https://github.com/Hackerpilot/dfmt)
>   - [dscanner](https://github.com/Hackerpilot/Dscanner)
> - Then, run:
>   
>   git clone https://github.com/Pure-D/workspace-d.git
>   cd workspace-d
>   dub build --build=release

**Comment by WebFreak001** [comment]
Thanks, totally forgot to update that because I just made that without thinking too much about it when I created it.
