### ISSUE TITLE
Register workspace-d on code.dlang.org

### ISSUE THREAD

**Issue by PetarKirov** [Pure-D/workspace-d#20]
Hi! I'm working on refactoring/improving the [installer](https://github.com/Pure-D/workspace-d/blob/master/installer/source/app.d) and it would be much easier w.r.t. automation if the project was on the dub registry - e.g. using `dub fetch`, instead of `mkdir tmpDir; git clone; git checkout; and so on`.

**Comment by WebFreak001** [comment]
how well would it work though? I mean dub is basically just meant for package managing.

Can you give me an example how the installing would look like if you use dub instead of git?

**Comment by PetarKirov** [comment]
I will post a PR later today that shows how I do it for the other dependencies (dcd, dscanner and dfmt). I just need to send a PR to dfmt to fix compilation with LDC before that.
(This issue is not a requirement for my PR, just a future improvement).

**Comment by WebFreak001** [comment]
https://code.dlang.org/packages/workspace-d

**Comment by PetarKirov** [comment]
Thanks!
