### ISSUE TITLE
Make a .deb

### ISSUE THREAD

**Issue by TurkeyMan** [Pure-D/workspace-d#22]
Your vscode addon `code-d` depends on this...
This in turn depends on `dub`, `dcd`, `dfmt`, `dscanner`. All of those packages are in d-apt (listed on the official download page: https://dlang.org/download.html)
Running `./install.sh` seems to want to fetch the deps, even though they are already installed on my machine (from d-apt)... This is not a user-friendly experience.
I think you need to make a `workspace-d.deb`, also put it on d-apt, and make the other dependency packages actual package dependencies. Then `code-d` can just instruct people to `apt install workspace-d`, and not mess with this cloning and building stuff.

**Comment by WebFreak001** [comment]
Good idea. I think I should also make the installer smarter and more friendly.

**Comment by Vild** [comment]
I don't really agree with this, for me the `install.sh/bat` file is a one click stop for setting up everything that is needed for workspace-d.
For just workspace-d you just need to run `dub build`.

For the deb package on d-apt I would suggest that you contact the maintainer for that repo.
You could link this to the maintainer as well: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=workspace-d . This is how I build the package for ArchLinux.

But we can't really recommend people to run `apt install workspace-d` because this would only apply to apt users.
If anything we could recommend that people should look in their package manager before manually compiling it.

**Comment by WebFreak001** [comment]
Well we can already recommend people to run `yaourt -S workspace-d`, so also adding it to the other package managers would actually make it easier to install

**Comment by TurkeyMan** [comment]
> `install.sh/bat` file is a one click stop for setting up everything that is needed for workspace-d.

dlang.org downloads page specifically recommends the d-apt repo for ubuntu/debian users. I think most people using those distros are using it. Therefore, the dependent tools are already available from the package manager, and possibly installed. I don't like that `install.sh` downloads and builds local versions of the apps I already have installed. A workspace-d.deb package would surely aim to be added to d-apt, and simply depend on the existing packages.

Also, I found that `install.sh` depends on dub, and on libcurl. I had neither installed and the script errored. Dub should obviously also be a dependency of a .deb package (libcurl was only used for building the tools).

> But we can't really recommend people to run apt install workspace-d because this would only apply to apt users.

Oh come on... every linux user expects that the "Install" part of the guide is split into sections for different distros, typically with a 'from source' section as well. There's nothing to lose here, just make deb users feel more comfortable, and vscode/atom users have only one package to install (auto-fetching dependencies).

**Comment by WebFreak001** [comment]
Releases are now going to contain download links for deb files. I didn't actually try if it worked, so if anyone could try them out would be nice.

However because DCD, Dscanner and dfmt are not part of this project, you need to manually install them once if you wish to use them with workspace-d

**Comment by TurkeyMan** [comment]
Great stuff!
I think it would be ideal to negotiate with the d-apt maintainer to have him host the deb in his repo alongside the other tools, then you can assign each of those tools as dependencies and apt can fetch them together.
