### ISSUE TITLE
dscanner package in AUR fails to build

### ISSUE THREAD

**Issue by TurkeyMan** [Pure-D/workspace-d#3]
`yaourt -S --aur dscanner` fails

```
...
libdparse/src/std/d/lexer.d(2240): Deprecation: asm statement is assumed to be impure - mark it with 'pure' if it is not
libdparse/src/std/d/lexer.d(2240): Deprecation: asm statement is assumed to use the GC - mark it with '@nogc' if it does not
libdparse/src/std/d/lexer.d(2240): Deprecation: asm statement is assumed to throw - mark it with 'nothrow' if it does not
makefile:28: recipe for target 'dmdbuild' failed
make: *** [dmdbuild] Error 1
```

Dependency on wrong DMD version?

**Comment by WebFreak001** [comment]
Which dmd version do you have? With dmd 2.069.1 it passes on their build server. If you use the same version consider reporting this to @Hackerpilot on https://github.com/Hackerpilot/Dscanner

**Comment by TurkeyMan** [comment]
[manu ~] $ dmd --version
DMD64 D Compiler v2.069

Close...

**Comment by Vild** [comment]
Discussion will continue on the Dscanner issue instead, closing this.
