### ISSUE TITLE
package for workspace-d in AUR?

### ISSUE THREAD

**Issue by TurkeyMan** [Pure-D/workspace-d#4]
the other 3 projects all have packages in the AUR, but workspace-d does not

**Comment by WebFreak001** [comment]
@Vild is the maintainer. I think he actually already added it to AUR. He will be able to tell you more because I don't have Arch

**Comment by Vild** [comment]
The package name i "workspace-d-git" just because there is no released version on git.
If you have ran "yaourt workspace-d" you would have found it in the list.

**Comment by TurkeyMan** [comment]
Damn it! Why doesn't `yaourt -S blah[tab][tab]` autocomplete and present the list of candidates like pacman and every other linux command line tool? It's unconventional to require a manual search >_<

**Comment by Vild** [comment]
Probably because how it works, every aur package it on the web and the db is never synced to your computer. 

I could recommend that you start to write "yaourt workspace-d" for example. This will give you a list where you can select the packages you want.

**Comment by TurkeyMan** [comment]
> Probably because how it works, every aur package it on the web and the db is never synced to your computer.

Oh, interesting. I didn't know that... that kinda seems like a design error though ;)

> I could recommend that you start to write "yaourt workspace-d" for example. This will give you a list where you can select the packages you want.

Yup, I understand the proper way to do it, I just forget. I've only recently switched to Arch.
