### ISSUE TITLE
Does not install from VS-Code

### ISSUE THREAD

**Issue by p0nce** [Pure-D/workspace-d#51]
When I compile from source from VS-Code, the following build error happens:

```
../../../../../.dub/packages/dub-1.1.0-beta.1/dub/source/dub/internal/sdlang/lexer.d(16,8): Error: module stream is in file 'std/stream.d' which cannot be read
```

**Comment by WebFreak001** [comment]
See https://github.com/dlang/dub/issues/952 https://github.com/Pure-D/code-d/issues/80

**Comment by WebFreak001** [comment]
oops, wrong repository

**Comment by WebFreak001** [comment]
Should be fixed now

**Comment by p0nce** [comment]
Thanks! Will try again :)
