### ISSUE TITLE
git clone not working, solve with --recursive

### ISSUE THREAD

**Issue by SrMordred** [Pure-D/workspace-d#58]
Since libdparse are a submodule, it only clone with workdspace-d if --recursive option are added. (normal git clone leaves the libdparse dir empty)
(I´m git noob, so if i´m saying something very stupid please ignore/edit )

**Comment by WebFreak001** [comment]
Should maybe add this to the README. Also you can use `git submodule update --init --recursive` on an already cloned repository to get the submodules

**Comment by p0nce** [comment]
Last time I've tried to install on OSX, I had to patch the installer to get git submodules to be downloaded. Same issue probably?

**Comment by WebFreak001** [comment]
yeah im gonna add it to the installer here and on vscode soon

**Comment by WebFreak001** [comment]
#64

**Comment by WebFreak001** [comment]
Didn't mean to close this

**Comment by p0nce** [comment]
Managed to install and use it on OSX! It's great! DCD warnings were a nice surprise.
On the downside, the debugging didn't work out of the box, I haven't look into it yet.

**Comment by WebFreak001** [comment]
you need to install code-debug, its a separate extension I made. Search for webfreak.debug and then also read the README on how to setup lldb for OSX for code-debug
