### ISSUE TITLE
Windows build fails (missing curl.lib)

### ISSUE THREAD

**Issue by CZDanol** [Pure-D/workspace-d#69]
When trying to build on windows, I get 
```
workspace-d 2.9.1+commit.12.gbd4921e: building configuration "application"...
Using Visual C++: D:\Programy\MSVC2015\VC
LINK : fatal error LNK1181: cannot open input file 'curl.lib'
```

**Comment by WebFreak001** [comment]
`ldc2 --version`?

Try redownloading the latest version maybe? Also is dmd installed alongside ldc?

**Comment by CZDanol** [comment]
```
LDC - the LLVM D compiler (1.2.0git-7e97c58):
  based on DMD v2.071.2 and LLVM 3.9.1git-a093ef4
  built with LDC - the LLVM D compiler (1.0.0)
  Default target: x86_64-pc-windows-msvc
  Host CPU: skylake
  http://dlang.org - http://wiki.dlang.org/LDC
```

Just downloaded. Yes it is.

**Comment by WebFreak001** [comment]
Clone master and try again now (its adding --combined to the dub call now)

**Comment by CZDanol** [comment]
Still nothing. I've succeded building it by building the curl by myself, but that was extra work I think should be avoided.

**Comment by CZDanol** [comment]
I actually get this

```
Upgrading project in D:\Programy\workspace-d
$ dub build --compiler=ldc2 --combined --build=release
Performing "release" build using ldc2 for x86.
workspace-d 2.9.1+commit.15.g36068ae: building configuration "application"...
Error: out of memory
ldc2 failed with exit code 1.
Error while compiling workspace-d.
```

now when trying to build using install.bat. I've tried before just using "dub build --build=release --compiler=ldc"

**Comment by WebFreak001** [comment]
Installed the 64 bit version of LDC? It won't work on 32 bit until compilation without --combined gets fixed by dub (dlang/dub#911)

**Comment by CZDanol** [comment]
Yes, I have 64bit version of LDC

**Comment by WebFreak001** [comment]
How much memory do you have? You need about 3.3GB of free RAM when compiling

**Comment by CZDanol** [comment]
My ram is 8GB, I've tried turning all apps of, which gave me about 4.5GB of space, still nothing. When watching memory usage in the task manager, it only raised by 1GB before throwing that error.

**Comment by WebFreak001** [comment]
Hm in my windows VM I am using this version of LDC:
```
LDC - the LLVM D compiler (1.1.0-beta3):
  based on DMD v2.071.2 and LLVM 3.9.0
  built with LDC - the LLVM D compiler (1.1.0-beta3)
  Default target: x86_64-pc-windows-msvc
  Host CPU: sandybridge
  http://dlang.org - http://wiki.dlang.org/LDC
```

I see that you are using a `git` version, I'm not sure if that will affect the compilation, try a precompiled windows binary from the releases page

**Comment by CZDanol** [comment]
Well, this is somehow surprising for me. When I downloaded the precompiled binary, I immediately noticed it has folders 'lib32' and 'lib64', both containing curl.lib :D Compiles now.
