### ISSUE TITLE
Bugs in automatic importing

### ISSUE THREAD

**Issue by CZDanol** [Pure-D/workspace-d#73]
- [x] Make automatic import search through phobos?
- [x] Also check "no property 'xx' for type 'xx'" errors (UFCS)
- [x] Automatic imports are not put on a separate line
- [x] When there are no imports, automatic imports are put before module statement

**Comment by WebFreak001** [comment]
1 and 2 are code-d issues, not workspace-d issues

**Comment by CZDanol** [comment]
Now it puts space before import statement. (only sometimes, maybe only when it's first import of the file?)

**Comment by WebFreak001** [comment]
Got 2.10.0 or above and at least two lines of code?

**Comment by CZDanol** [comment]
2.10.1, you can test it on https://github.com/beast-lang/compiler/blob/master/src/beast/project/modulemgr/modulemgr.d by removing the import line and then auto-fixing it
