### ISSUE TITLE
Intellisense does not work on non-imported symbols

### ISSUE THREAD

**Issue by CZDanol** [Pure-D/workspace-d#75]
In module a I have:
```
module a;
struct S {
 int x;
};
```

in module b:
```
module b;
import c;
S s;
```

and when I have module c:
```
module c;
import b;

void main() {
  s.x = 5; // intellisense does not pop here
}
```

**Comment by WebFreak001** [comment]
well this would fail to compile. `module a` is never imported in any of those 2 files, it must be imported in `module b` for it to work. So if it fails to compile it shouldn't work there and this behavior is also expected from the programmer because it could be 2 separate "projects" there because they have no dependency on each other whatsoever.

**Comment by CZDanol** [comment]
I have a typo in module b, there should be import c;

**Comment by WebFreak001** [comment]
That doesn't change your code?

**Comment by CZDanol** [comment]
O_o typo again, import a;

**Comment by CZDanol** [comment]
I will put together a sample project.

**Comment by WebFreak001** [comment]
Well in that case it works for me, try using longer struct & field names than one letter, one letter doesn't trigger intellisense on global scope

**Comment by WebFreak001** [comment]
```d
// hello.d
module hello;

import foo;

void main() {
	b // includes bar
	bar. // shows world
}
```
```d
// foo.d
module foo;

import bar;

Bar bar;
```
```d
// bar.d
module bar;

struct Bar
{
	int world;
}
```

**Comment by CZDanol** [comment]
I've experienced this in my real project with real identifiers. Sorry, my bad for not finding the correct error case, will report when I document it properly.

**Comment by WebFreak001** [comment]
On which scope? Members of the variable or completing the global variable name?

**Comment by CZDanol** [comment]
variable members

**Comment by WebFreak001** [comment]
Hm then it's a weird bug, try finding a reproducable test case. It could be unicode characters in that file (they sometimes mess up things), it could be because it uses something else (like a module name) instead of the variable, etc.

**Comment by CZDanol** [comment]
Yes, I am so sorry for annying with not-working-bug-report-cases :/
