### ISSUE TITLE
Module naming toolkit

### ISSUE THREAD

**Issue by CZDanol** [Pure-D/workspace-d#78]
* [x] When creating a new `.d` file, automatically (or prompt) add `module x.y.z;` statement to it
* [x] When renaming a `.d` file, change the module name in the module statement
* [x] When renaming a directory that contains `.d` files, change the package name in their module statements
* [x] When moving a directory or `.d` file, change the module statements appropriately
* [x] Do the same with all import statements in the project for all cases above

**Comment by WebFreak001** [comment]
* should be implemented by frontend
* should be implemented by frontend
* should be implemented by frontend
* should be implemented by frontend
* ok, can do

I guess adding a method to rename the module is a good idea for the frontend
