### ISSUE TITLE
2.11.0 Keeps crashing from vscode

### ISSUE THREAD

**Issue by testing-in-chrome** [Pure-D/workspace-d#83]
I compiled it with the new version of the compiler 2.075.0, and it doesn't work anymore! vscode keeps showing the following notifications:

Workspace-D crashed, please kill dcd-server if necessary.

[screenshot](https://drive.google.com/file/d/0B9NoD5ZlZAEMaWxXZy1LZC1rZ0k/view?usp=sharing)

**Comment by WebFreak001** [comment]
by the font I assume you are on ubuntu, can you open the developer tools (Ctrl-Shift-P -> Toggle Developer Tools) and send a screenshot from there?

**Comment by testing-in-chrome** [comment]
Yes, Ubuntu 16.04.

There you go

![screenshot](https://snag.gy/VTfOCt.jpg)

**Comment by testing-in-chrome** [comment]
By the way, in case you are wondering, I'm not going out of memory! I have PLENTY of free memory.

**Comment by testing-in-chrome** [comment]
Any updates here? This made me switch to [dlang-vscode](https://github.com/dlang-vscode/dlang-vscode) for now!

**Comment by testing-in-chrome** [comment]
This is still not fixed. Please reopen.

![screenshot](https://snag.gy/CcMJzy.jpg)

**Comment by WebFreak001** [comment]
did you recompile it yet? I didn't push it to auto update in code-d yet

**Comment by testing-in-chrome** [comment]
Yes, I did recompile it.

**Comment by testing-in-chrome** [comment]
Still happening even with the new beta extension:

2017-08-11T17:04:21.304:extension.d:initialize:150 Starting dub...
2017-08-11T17:04:21.950:app.d:__lambda10:236 Failed processing request: core.exception.OutOfMemoryError@src/core/exception.d(696): Memory allocation failed
----------------
{"code":-32603,"data":"core.exception.OutOfMemoryError@src\/core\/exception.d(696): Memory allocation failed\n----------------","message":"Memory allocation failed"}
2017-08-11T17:04:21.950:jsonrpc.d:send:66 {"error":{"code":-32603,"data":"core.exception.OutOfMemoryError@src/core/exception.d(696): Memory allocation failed\n----------------","message":"Memory allocation failed"},"jsonrpc":"2.0"}

**Comment by WebFreak001** [comment]
can you post your `uname -a && free -h` output?

**Comment by testing-in-chrome** [comment]
4.10.0-32-generic Pure-D/serve-d#201~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
              total        used        free      shared  buff/cache   available
Mem:            31G        1.2G         27G        1.2G        2.2G         28G
Swap:            0B          0B          0B

**Comment by testing-in-chrome** [comment]
So I reverted back to the previous dmd compiler (DMD 2.074.1) and recompiled both workspace-d and serve-d and everything is now working as expected. It no longer crashes.

So to be clear, this crash only happens when you compile with DMD 2.075.0

I'm surprised that no one else reported this crash. I assume it's because they already have workspace-d compiled from before using the previous dmd version and there's no need to recompile it. But this will certainly be an issue for your new users.

It could be a compiler bug, but you'd probably need to confirm this and why and then file a bug against dmd. If you mainly develop on Windows, please consider reproducing this crash on an Ubuntu virtual machine or something. It happens all the time.

**Comment by WebFreak001** [comment]
I only develop on archlinux with dmd v2.075.0 and that bug never happens to me. Does it happen with every project (even a hello world project) or just with a few projects? Well it can't only be DMDs fault because I suppose your projects you compile with DMD work. Can you try disabling the memory error handler (remove [source/app.d:359-361](https://github.com/Pure-D/workspace-d/blob/master/source/app.d#L359-L361)), recompile and send me the new stacktrace?

**Comment by testing-in-chrome** [comment]
It doesn't crash on a hello world project (though it doesn't work at all -- no autocomplete, no jump to definition, ... nothing), but it crashes on these projects I tried: tilix, dlangui, dlangide, tkd, ... etc.

Removed the lines you suggested, but it doesn't produce any stack traces when it crashes.

**Comment by WebFreak001** [comment]
oh right now you need to run it using gdb... uh which isn't possible with code-d/workspace-d but only with serve-d, can you first try if serve-d: install code-d-beta in vscode) crashes and if it does try running it as extension host (install gdbserver, clone code-d, `git checkout serve-d`, `npm install`, `tsc -p .`, open in vscode, go to debug tab, click start && clone serve-d, open in vscode, go to debug tab, select attach to running serve-d instance in the drop down and hit start, click continue a few times if it pauses and wait until the stacktrace.

**Comment by testing-in-chrome** [comment]
I haven't had a chance to do what you suggested, and likely I won't have time to do it soon. Please try to repro in a VM. It can easily be repro'd on Ubuntu and OpenSuse Tubmleweed. Just build with the most recent compiler by running `./install.sh`, add the resulting `bin` dir to your `$PATH` and open vscode on one of the D projects I mentioned before. It crashes right away on initialization.

**Comment by WebFreak001** [comment]
no problem in a Ubuntu VM with 2GB memory + 2GB swap, memory usage is constantly around 800mb too

**Comment by vladimmi** [comment]
Returned to VS Code and D after some time. This still happens under Windows.
```Workspace-D crashed. Please kill dcd-server if necessary!```
...as notify and...
```[Extension Host] WorkspaceD ended with code 3221225477```
...only in developer console.
There was (or still is) copy of workspace-d 2.10 - it wasnt crashing, but workspace-d 2.11 and serve-d crash all the time for unknown reason.

**Comment by WebFreak001** [comment]
probably fixed with latest versions
