### ISSUE TITLE
Crashes with source-libraries

### ISSUE THREAD

**Issue by vladimmi** [Pure-D/workspace-d#86]
To reproduce:
- create empty project
- set `"targetType": "sourceLibrary"` in `dub.json`
- reload window to see `Workspace-D crashed. Please kill dcd-server if neccessary!` warning and `[Extension Host] WorkspaceD ended with code 3221225477` message in devtools console.

**Comment by MasterDomino** [comment]
exactly the same error code 3221225477 fresh clone of all dependencies, tried a few things, also dont forget there was a configuration issue with dscanner path from the start

"d.dscannerPath": "Z:\\Users\\usr\\.vscode\\extensions\\webfreak.code-d-0.16.2\\bin\\Dscanner\\dscanner.exe" <- that is also an issue need to have additional \\bin\\ after dscanner folder.
