### ISSUE TITLE
macOS compile failure

### ISSUE THREAD

**Issue by joelcnz** [Pure-D/workspace-d#87]
I'm using a macOS (10.12.6) computer. workspace-d used to work, but now it says it's not installed, (I think since I quit out of Visual Code before shutting down the computer). I tried compiling with with the option, but got this (see below). Also, I went to wipe off ~/.dub/packages/workspace-d, and it didn't exist, neither did serve-d. I tried compiling it seperately, but got the same errors.

Installing into /Users/joelchristensen/.vscode/extensions/webfreak.code-d-0.16.3/bin
Removing old version
Removed old version
> git clone --recursive --depth=1 https://github.com/Pure-D/workspace-d.git workspace-d
Cloning into 'workspace-d'...
> dub upgrade
Upgrading project in /Users/joelchristensen/.vscode/extensions/webfreak.code-d-0.16.3/bin/workspace-d
> dub build --build=release
Performing "release" build using dmd for x86_64.
libdparse 0.8.0-alpha.3: target for configuration "library" is up to date.
dfmt 0.6.0-alpha.1: target for configuration "library" is up to date.
emsi_containers 0.5.3: target for configuration "library" is up to date.
dsymbol 0.2.9: building configuration "library"...
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(189,15): Error: no property 'symbol' for type 'const(Type2)'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(189,42): Error: no property 'symbol' for type 'const(Type2)'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(192,23): Error: no property 'symbol' for type 'const(Type2)'
../../../../../.dub/packages/emsi_containers-0.5.3/emsi_containers/src/containers/unrolledlist.d(504,15): Deprecation: integral promotion not done for `~this.registry`, use '-transition=intpromote' switch or `~cast(int)(this.registry)`
../../../../../.dub/packages/emsi_containers-0.5.3/emsi_containers/src/containers/unrolledlist.d(504,15): Deprecation: integral promotion not done for `~this.registry`, use '-transition=intpromote' switch or `~cast(int)(this.registry)`
../../../../../.dub/packages/emsi_containers-0.5.3/emsi_containers/src/containers/unrolledlist.d(504,15): Deprecation: integral promotion not done for `~this.registry`, use '-transition=intpromote' switch or `~cast(int)(this.registry)`
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(248,35): Error: no property 'identifierList' for type 'const(AliasDeclaration)'
../../../../../.dub/packages/emsi_containers-0.5.3/emsi_containers/src/containers/unrolledlist.d(504,15): Deprecation: integral promotion not done for `~this.registry`, use '-transition=intpromote' switch or `~cast(int)(this.registry)`
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(938,14): Error: no property 'symbol' for type 'const(Type2)'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/conversion/first.d(939,18): Error: no property 'symbol' for type 'const(Type2)'
../../../../../.dub/packages/emsi_containers-0.5.3/emsi_containers/src/containers/unrolledlist.d(504,15): Deprecation: integral promotion not done for `~this.registry`, use '-transition=intpromote' switch or `~cast(int)(this.registry)`
../../../../../.dub/packages/emsi_containers-0.5.3/emsi_containers/src/containers/unrolledlist.d(504,15): Deprecation: integral promotion not done for `~this.registry`, use '-transition=intpromote' switch or `~cast(int)(this.registry)`
../../../../../.dub/packages/emsi_containers-0.5.3/emsi_containers/src/containers/unrolledlist.d(504,15): Deprecation: integral promotion not done for `~this.registry`, use '-transition=intpromote' switch or `~cast(int)(this.registry)`
../../../../../.dub/packages/emsi_containers-0.5.3/emsi_containers/src/containers/unrolledlist.d(504,15): Deprecation: integral promotion not done for `~this.registry`, use '-transition=intpromote' switch or `~cast(int)(this.registry)`
../../../../../.dub/packages/emsi_containers-0.5.3/emsi_containers/src/containers/unrolledlist.d(504,15): Deprecation: integral promotion not done for `~this.registry`, use '-transition=intpromote' switch or `~cast(int)(this.registry)`
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/semantic.d(123,21): Error: no property 'symbol' for type 'dparse.ast.Type2'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/semantic.d(124,21): Error: no property 'symbol' for type 'dparse.ast.Type2'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/semantic.d(128,21): Error: no property 'symbol' for type 'dparse.ast.Type2'
../../../../../.dub/packages/dsymbol-0.2.9/dsymbol/src/dsymbol/semantic.d(130,21): Error: no property 'symbol' for type 'dparse.ast.Type2'
dmd failed with exit code 1.
Failed to install workspace-d (Error code 2)

**Comment by WebFreak001** [comment]
this seems like an issue with dub. On some machines I can reproduce it, on some I can't. When I ask others who already had older versions nobody could reproduce it.

**Comment by Cody-Duncan** [comment]
Can confirm this occurs on Windows too.

```
..\..\Users\NAME\AppData\Roaming\dub\packages\dsymbol-0.2.9\dsymbol\src\dsymbol\conversion\first.d(189,15): Error: no property 'symbol' for type 'const(Type2)'
..\..\Users\NAME\AppData\Roaming\dub\packages\dsymbol-0.2.9\dsymbol\src\dsymbol\conversion\first.d(189,42): Error: no property 'symbol' for type 'const(Type2)'
..\..\Users\NAME\AppData\Roaming\dub\packages\dsymbol-0.2.9\dsymbol\src\dsymbol\conversion\first.d(192,23): Error: no property 'symbol' for type 'const(Type2)'
..\..\Users\NAME\AppData\Roaming\dub\packages\dsymbol-0.2.9\dsymbol\src\dsymbol\conversion\first.d(248,35): Error: no property 'identifierList' for type 'const(AliasDeclaration)'
..\..\Users\NAME\AppData\Roaming\dub\packages\dsymbol-0.2.9\dsymbol\src\dsymbol\conversion\first.d(938,14): Error: no property 'symbol' for type 'const(Type2)'
..\..\Users\NAME\AppData\Roaming\dub\packages\dsymbol-0.2.9\dsymbol\src\dsymbol\conversion\first.d(939,18): Error: no property 'symbol' for type 'const(Type2)'
..\..\Users\NAME\AppData\Roaming\dub\packages\dsymbol-0.2.9\dsymbol\src\dsymbol\semantic.d(123,21): Error: no property 'symbol' for type 'dparse.ast.Type2'
..\..\Users\NAME\AppData\Roaming\dub\packages\dsymbol-0.2.9\dsymbol\src\dsymbol\semantic.d(124,21): Error: no property 'symbol' for type 'dparse.ast.Type2'
..\..\Users\NAME\AppData\Roaming\dub\packages\dsymbol-0.2.9\dsymbol\src\dsymbol\semantic.d(128,21): Error: no property 'symbol' for type 'dparse.ast.Type2'
..\..\Users\NAME\AppData\Roaming\dub\packages\dsymbol-0.2.9\dsymbol\src\dsymbol\semantic.d(130,21): Error: no property 'symbol' for type 'dparse.ast.Type2'
```

**Comment by Cody-Duncan** [comment]
.\src\dsymbol\conversion\first.d(189,15): Error: no property 'symbol' for type 'const(Type2)'
Caused by the line in src/dsymbol/conversion/first.d
	`if (bc.type2.symbol is null || bc.type2.symbol.identifierOrTemplateChain is null)`
The BaseClass's member "symbol" was removed as a part of fix #158 of libdparse (https://github.com/dlang-community/libdparse/issues/158), integrated in libdparse v0.8.0-alpha.1
	
dsymbol has since replaced that with
	`if (bc.type2.typeIdentifierPart is null || bc.type2.typeIdentifierPart.identifierOrTemplateInstance is null)`
as of this commit https://github.com/dlang-community/dsymbol/commit/e10a99fedcd00c0fe48fc56890f3a1ea9172ac0d
part of dsymbol v0.3.0-beta.3, but it looks like was included in dsymbol v0.3.0-beta.1
	
Upgrading to dsymbol v0.3.0-beta.1 fixes the issue.
	
However, a new error occurs...
..\..\Users\Dragon\AppData\Roaming\dub\packages\dscanner-0.4.2\dscanner\src\astprinter.d(1095,16): Error: undefined identifier IdentifierList
Looks like IdentifierList stopped existing.
As of Fix #158 to libdparse https://github.com/dlang-community/libdparse/issues/158,
IdentifierList was renamed to DeclaratorIdentifierList
	
Dscanner adopted changes for the latest version of libdparse (like renaming to DeclaratorIdentifierList) as a part of commit https://github.com/dlang-community/D-Scanner/commit/10bf4725c0f579262c27bad872197b09bd7adad8
	
There has not been a new release of dscanner since this change was adopted.

**Comment by Cody-Duncan** [comment]
Upgrading the dub.selection.json: 
"dsymbol": "0.3.0-beta.3",

and the dependency on dscanner in dub.json
"dscanner": "~master",

encounters these errors, which appear as though these files have not yet updated to match the dependency on dsymbol 0.3.0-beta.1
```
source\workspaced\com\dcdext.d(178,36): Error: no property 'symbol' for type 'const(Type2)'
source\workspaced\com\dcdext.d(178,58): Error: no property 'symbol' for type 'const(Type2)'
source\workspaced\com\dcdext.d(179,22): Error: no property 'symbol' for type 'const(Type2)'
source\workspaced\com\dcdext.d(183,23): Error: no property 'symbol' for type 'const(Type2)'
source\workspaced\com\dscanner.d(535,10): Error: no property 'identifierList' for type 'const(AliasDeclaration)'
source\workspaced\com\dscanner.d(536,19): Error: no property 'identifierList' for type 'const(AliasDeclaration)'
```

**Comment by Cody-Duncan** [comment]
I'm not certain there will be any way to fix this nicely until dscanner has a new release. 

For getting workspace-d installed on Visual Studio Code via either the code-d or serve-d extensions. This example is getting it to work for the code-d serve-d Beta extension. 
https://marketplace.visualstudio.com/items?itemName=webfreak.code-d-beta

**Workaround:**

0. Open Visual Studio Code. Let it try to build code-d/serve-d and fail.

1. Manually navigate to the directory for serve-d.
serve-d on windows: C:\Users\NAME\AppData\Roaming\code-d\bin\serve-d

2. downgrade libdparse to a compatible version in the dub.selections.json
`"libdparse": "0.7.2-alpha.6",`

3. build serve-d
`dub build --arch=x86_mscoff`

4. Set your user settings to point at the serve-d executable.
File -> Preferences -> Settings
Search for "d.servedPath"
Set to the path you built serve-d from step #1 and append "/serve-d.exe" ("\\\\serve-d.exe" on windows)
Note: This step prevents the code-d/serve-d plugin from refetching and rebuilding, which overwrites the changes in step #2

5. Restart Visual Studio Code.

**Comment by WebFreak001** [comment]
yeah we can only use workarounds right now as they will probably not do anything against it, see https://github.com/dlang-community/dsymbol/issues/61

**Comment by WebFreak001** [comment]
Since the new dub release you can see that this is indeed an issue with conflicting versions of libdparse because of dfmt and dscanner (but also fluent-asserts and libddoc)

```
Root package workspace-d reference libdparse >=0.0.0 cannot be satisfied.
Packages causing the conflict:
	dfmt depends on >=0.8.0-alpha.5 <0.9.0
	workspace-d depends on >=0.0.0
	fluent-asserts:core depends on >=0.7.2-alpha.3 <0.8.0-0
	fluent-asserts depends on >=0.7.2-alpha.3 <0.8.0-0
	dsymbol depends on ~>0.7.1
	dsymbol depends on >=0.7.1-beta.7 <0.8.0
	dsymbol depends on >=0.7.1-beta.7 <0.8.0
	dsymbol depends on >=0.7.1-beta.7 <0.8.0
	libddoc depends on >=0.7.0-alpha10 <0.8.0
	dscanner depends on >=0.7.2-alpha.5 <0.8.0-0
```

**Comment by WebFreak001** [comment]
as I didn't see any other way out right now I pinned dfmt to a fixed version to avoid breakage.
